import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// PLACEHOLDER Firebase configuration.
///
/// This file is normally generated by the FlutterFire CLI. Until you generate
/// the real one, [currentPlatform] throws — `main()` catches that and runs the
/// app in **guest mode** so nothing crashes before Firebase is set up.
///
/// To enable real authentication (see SETUP.md):
/// ```
/// dart pub global activate flutterfire_cli
/// flutterfire configure
/// ```
/// That command overwrites this file with your project's keys, after which
/// email/password and Google sign-in work for real.
class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'Firebase is not configured yet. Run `flutterfire configure` to generate '
      'lib/firebase_options.dart with your project keys. See SETUP.md for the '
      'full setup, including the Google sign-in steps (SHA-1 / URL scheme).',
    );
  }
}
